/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.JardinController;
import Model.Actores.Ninno;
import Model.Grupo;
import Model.Logro;
import Persistencia.ReportPrinter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * JFrame para la vista del acudiente, donde podra ver la informacion de su ninno
 * @author Royk
 */
public class AcudienteGUI extends javax.swing.JFrame {
    private Ninno ninno;
    private Login login;
    
            
    /**
     * Creates new form AcudienteGUI
     */
    public AcudienteGUI() {
        initComponents();
    }
    
    /**
     * Constructor basico que recibe el ninno a mostrar y la ventana login padre de esta
     * @param ninno
     * @param login 
     */
    public AcudienteGUI(Ninno ninno, Login login){
        initComponents();
        this.ninno = ninno;
        this.login = login;
        llenarInformacion();
    }
    
    /**
     * Metodo que llena los la informacion personal de los ninnos y sus logros
     */
    public void llenarInformacion(){
        llenarDetalles();
        llenarLogros();
    }
    
    /**
     * Metodo que llena las etiquetas con informacion personal del ninno
     */
    public void llenarDetalles(){
        nombreLabel.setText(ninno.getNombreCompleto());
        
        int numGrupo = ninno.getGrupo();
        Grupo grupo = JardinController.getGrupo(numGrupo);
        grupoLabel.setText(grupo.getId());
        nivelLabel.setText(Integer.toString(grupo.getNivel()));
        profesorLabel.setText(grupo.getProfesor().getNombreCompleto());
        telefonoLabel.setText(grupo.getProfesor().getTelefono());
    }
    
    /**
     * Metodo que llena la tabla de logros del ninno
     */
    public void llenarLogros(){
        DefaultTableModel table = (DefaultTableModel) logrosTabla.getModel();
        ArrayList<Logro> logros = ninno.getLogros();
        
        for(Logro logro: logros){
            table.addRow(new Object[]{logro.getBimestreString(), logro.getTitulo(), logro.getEstado()});
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tittleLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nivelLabel = new javax.swing.JLabel();
        grupoLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        profesorLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        telefonoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logrosTabla = new javax.swing.JTable();
        verLogroBoton = new javax.swing.JButton();
        imprimirBoton = new javax.swing.JButton();
        salirBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tittleLabel.setText("Informacion del Niño");

        nombreLabel.setText("nombre");

        jLabel1.setText("Nivel");

        jLabel2.setText("Grupo");

        nivelLabel.setText("jLabel3");

        grupoLabel.setText("jLabel4");

        jLabel3.setText("Profesor");

        profesorLabel.setText("jLabel4");

        jLabel5.setText("Telefono");

        telefonoLabel.setText("jLabel6");

        logrosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bimestre", "Logro", "Avance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(logrosTabla);

        verLogroBoton.setText("Ver Logro");
        verLogroBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verLogroBotonActionPerformed(evt);
            }
        });

        imprimirBoton.setText("Imprimir Reporte");
        imprimirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirBotonActionPerformed(evt);
            }
        });

        salirBoton.setText("Salir");
        salirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tittleLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nivelLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grupoLabel)))
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(telefonoLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(profesorLabel)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(verLogroBoton)
                                .addGap(18, 18, 18)
                                .addComponent(imprimirBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(salirBoton)))
                        .addGap(0, 16, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tittleLabel)
                .addGap(34, 34, 34)
                .addComponent(nombreLabel)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(nivelLabel)
                    .addComponent(profesorLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grupoLabel)
                    .addComponent(telefonoLabel)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verLogroBoton)
                    .addComponent(imprimirBoton)
                    .addComponent(salirBoton))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Boton que muestra la descripcion del logro seleccionado
     * @param evt 
     */
    private void verLogroBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verLogroBotonActionPerformed
        if(logrosTabla.getModel().getRowCount() > 0){
            String logroTitulo = logrosTabla.getModel().getValueAt(logrosTabla.getSelectedRow(), 1).toString();
            Logro logro = ninno.getLogro(logroTitulo);
            
            if(logro != null){
                JOptionPane.showMessageDialog(this, logro.getDescripcion(), logroTitulo, JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_verLogroBotonActionPerformed

    /**
     * Boton para salir de la ventana de AcudienteGUI y volver al login
     * @param evt 
     */
    private void salirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBotonActionPerformed
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_salirBotonActionPerformed

    /**
     * Boton para generar un documento pdf con la informacion del ninno y sus logros
     * @param evt 
     */
    private void imprimirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirBotonActionPerformed
        ReportPrinter printer = new ReportPrinter(ninno, "Historico");
        printer.imprimirPDF();
        JOptionPane.showMessageDialog(this, "Reporte creado, ver Archivo pdf", "Reporte Creado", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_imprimirBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcudienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcudienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcudienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcudienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcudienteGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel grupoLabel;
    private javax.swing.JButton imprimirBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable logrosTabla;
    private javax.swing.JLabel nivelLabel;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel profesorLabel;
    private javax.swing.JButton salirBoton;
    private javax.swing.JLabel telefonoLabel;
    private javax.swing.JLabel tittleLabel;
    private javax.swing.JButton verLogroBoton;
    // End of variables declaration//GEN-END:variables
}
